// REDUX ACTION TYPES
export const SETALLPOSTS = 'ALLPOSTS'
export const UPDATEPOSTS = 'UPDATEPOSTS'
export const DELETEPOST = 'DELETEPOST'
export const CREATE_POST = 'CREATE_POST'
export const CHANGE_POST = 'CHANGE_POST'
export const CREATE_COMMENT = 'CREATE_COMMENT'
